apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/migration

# Image tag set by CI/CD via:
#   kustomize edit set image migrator=REGISTRY/migrator:SHA
images:
- name: migrator
  newName: migrator
  newTag: latest
