apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moonpay

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

# Image tag set by CI/CD via:
#   kustomize edit set image nextjs=REGISTRY/nextjs:TAG
images:
  - name: nextjs
    newName: nextjs
    newTag: latest
