apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

# Image tag set by CI/CD via:
#   kustomize edit set image migrator=REGISTRY/migrator:TAG
images:
  - name: migrator
    newName: migrator
    newTag: latest
