apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Image tags are set by CI/CD via:
#   kustomize edit set image nextjs=REGISTRY/nextjs:SHA
#   kustomize edit set image migrator=REGISTRY/migrator:SHA
images:
  - name: nextjs
    newName: nextjs
    newTag: latest
  - name: migrator
    newName: migrator
    newTag: latest
