apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moonpay

resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - nextjs/deployment.yaml
  - nextjs/service.yaml
  - nextjs/hpa.yaml
  - nextjs/migration-job.yaml
